### ISSUE TITLE
CRT status LED is not functional

### ISSUE THREAD

**Issue by osresearch** [osresearch/mdt9100#9]
There is a red status LED on the bottom of the CRT.

**Comment by phooky** [comment]
This is pin 24 on the ribbon connector. There's a 2.2K resistor in line so presumably you just need to put 5V over it.

**Comment by osresearch** [comment]
Awesome, thanks for the update on this and the function keys.  By process of elimination, it sounds like the emergency lamp is pin 26? (issue #7 )
